#+TITLE: Emacs Config File
#+AUTHOR: F. Jerrell Schivers
#+EMAIL: jerrell@bordercore.com

Inspired by http://pages.sachachua.com/.emacs.d/Sacha.html

* Table of Contents                                                     :TOC:
- [[#emacs-initialization][Emacs initialization]]
- [[#packages][Packages]]
  - [[#sources][Sources]]
  - [[#setup][Setup]]
- [[#general-configuration][General Configuration]]
  - [[#misc][Misc]]
  - [[#help-and-documentation][Help and Documentation]]
  - [[#scratch-buffer][Scratch Buffer]]
  - [[#user-interface][User Interface]]
  - [[#key-bindings][Key Bindings]]
  - [[#backups][Backups]]
  - [[#buffers][Buffers]]
  - [[#sessions][Sessions]]
  - [[#typing-and-spelling][Typing and Spelling]]
  - [[#file-editing][File Editing]]
  - [[#window-management][Window Management]]
- [[#navigation][Navigation]]
  - [[#general][General]]
  - [[#completions][Completions]]
  - [[#imenu][Imenu]]
  - [[#projectile][Projectile]]
  - [[#search][Search]]
  - [[#treemacs][Treemacs]]
- [[#dired][Dired]]
- [[#org-mode][Org Mode]]
  - [[#items][items]]
  - [[#auto-show-emphasis-markers][Auto-show Emphasis Markers]]
  - [[#eye-candy][Eye Candy]]
- [[#development][Development]]
  - [[#misc-1][Misc]]
  - [[#language-server-protocol-lsp][Language Server Protocol (LSP)]]
  - [[#python][Python]]
  - [[#web-development][Web Development]]
  - [[#productivity][Productivity]]
  - [[#lisp][Lisp]]
  - [[#magit][Magit]]
  - [[#diff-hl][diff-hl]]
  - [[#yaml][YAML]]
- [[#ai][AI]]
  - [[#chatgpt][ChatGPT]]
  - [[#codeium][Codeium]]
- [[#external-tools-and-integration][External Tools and Integration]]
- [[#games][Games]]
  - [[#nethack][Nethack]]
- [[#runtime-performance][Runtime Performance]]
- [[#theme][Theme]]
- [[#wrapup][Wrapup]]

* Emacs initialization

Add /opt/local/bin to the exec-path. Aspell, which is used by
flyspell-mode, is installed here by MacPorts on OS X.
#+BEGIN_SRC emacs-lisp
(when (file-directory-p "/opt/local/bin")
  (add-to-list 'exec-path "/opt/local/bin"))
#+END_SRC

Suppress native-compiler warnings during startup
#+BEGIN_SRC emacs-lisp
(setq native-comp-async-report-warnings-errors nil)
#+END_SRC

Third party packages go here
#+BEGIN_SRC emacs-lisp
(add-to-list 'load-path "~/.emacs.d/elisp")
#+END_SRC

Start the Emacs server
#+BEGIN_SRC emacs-lisp
(server-start)
#+END_SRC

Look for an optional local.el file which contains code that is not meant to be checked-in.
#+begin_src emacs-lisp
(let ((local-file (expand-file-name "local.el" user-emacs-directory)))
  (when (file-exists-p local-file)
    (load local-file)))
#+end_src

* Packages
** Sources

#+BEGIN_SRC emacs-lisp
(require 'package)

(defmacro when-package-installed (package-name &rest body)
  `(if (package-installed-p ,package-name)
     (progn ,@body)
     (warn "package %s is not installed" ,package-name)))
(setplist 'when-package-installed '(lisp-indent-function defun))
#+END_SRC

Add the Marmalade and MELPA external repos to ELPA
#+BEGIN_SRC emacs-lisp
(add-to-list 'package-archives '("melpa-stable" . "http://stable.melpa.org/packages/") t)
(add-to-list 'package-archives '("melpa" . "http://melpa.org/packages/") t)
#+END_SRC

** Setup

Configure use-package
#+BEGIN_SRC emacs-lisp
(eval-when-compile
  (require 'use-package))
;; Ensure that packages are installed automatically if not already present on your system
(setq use-package-always-ensure t)
;; Packages that take longer than 0.1s to load are logged in the *Messages* buffer
(setq use-package-verbose t)
#+END_SRC

Use Paradox for modernizing the package menu
#+BEGIN_SRC emacs-lisp
(use-package paradox
  :init
  (setq paradox-github-token t)
  (setq paradox-execute-asynchronously nil)
  :config
  (paradox-enable))
#+END_SRC

* General Configuration
** Misc

Change 'yes or no' prompt to 'y or n' prompts
#+BEGIN_SRC emacs-lisp
(fset 'yes-or-no-p 'y-or-n-p)
#+END_SRC

Stop at the end of a file when moving the cursor down, don't just add lines
#+BEGIN_SRC emacs-lisp
(setq next-line-add-newlines nil)
#+END_SRC

TODO: Is there a better section for this?
makes killing/yanking interact with clipboard X11 selection
#+BEGIN_SRC emacs-lisp
(when (eq window-system 'x)
  (setq x-select-enable-clipboard t))
#+END_SRC

Flash the frame to represent a bell rather than play a sound
#+BEGIN_SRC emacs-lisp
(setq visible-bell t)
#+END_SRC

Always show trailing whitespace and tabs, but don't show a glyph for tabs
#+BEGIN_SRC emacs-lisp
(setq whitespace-style
      '(face empty tabs tab-mark trailing))
(setq whitespace-display-mappings
      '(
        (tab-mark 9 [9])
        ))
(global-whitespace-mode 1)
#+END_SRC

Delete trailing whitespace on save
#+begin_src emacs-lisp
  (add-hook 'before-save-hook 'delete-trailing-whitespace)
#+end_src

Enable visual-line-mode, which (among other things) makes lines wrap at word boundaries
#+BEGIN_SRC emacs-lisp
(global-visual-line-mode t)
#+END_SRC

Disable the startup screen
#+BEGIN_SRC emacs-lisp
(setq inhibit-startup-screen t)
#+END_SRC

Allow functions to operate on the current line when they would normally operate on the region,
eg kill-region when no region is selected will delete the current line.
See http://www.emacswiki.org/WholeLineOrRegion#toc3.
Most useful feature: C-w will delete the current line if no region is selected.
#+BEGIN_SRC emacs-lisp
(use-package whole-line-or-region
  :ensure t
  :config
  (whole-line-or-region-mode 1))
#+END_SRC

auto-save buffers when switching between buffers or when an Emacs frame lose focus
#+BEGIN_SRC emacs-lisp
(use-package super-save
  :delight
  :config
(super-save-mode +1))
#+END_SRC

Avoid "Symbolic link to Git-controlled source file; follow link?" prompt
by automatically answering "Yes". This only works when opening up new files.
It does not apply to existing files that need to be opened on startup
due to session saving.
#+BEGIN_SRC emacs-lisp
(setq vc-follow-symlinks t)
#+END_SRC

Whenever the window scrolls a light will shine on top of your cursor so you know where it is.
#+begin_src emacs-lisp
(use-package beacon
  :delight
  :ensure t
  :config
  (beacon-mode 1))
#+end_src

Disabling "auto-window-vscroll" improves scroll performance
#+begin_src emacs-lisp
(setq auto-window-vscroll nil)
#+end_src

** Help and Documentation

Helpful is an alternative to the built-in Emacs help that provides much more contextual information
#+BEGIN_SRC emacs-lisp
(use-package helpful
  :bind ("C-h f" . #'helpful-callable)
  :bind ("C-h v" . #'helpful-variable)
  :bind ("C-h k" . #'helpful-key)
  :config
  (add-hook 'lisp-mode-hook
            (lambda () (local-set-key (kbd "C-c C-d") #'helpful-at-point)))
  (add-hook 'lisp-mode-hook
            (lambda () (local-set-key (kbd "C-h F") #'helpful-function)))
  (add-hook 'emacs-lisp-mode-hook
            (lambda () (local-set-key (kbd "C-c C-d") #'helpful-at-point)))
  (add-hook 'emacs-lisp-mode-hook
            (lambda () (local-set-key (kbd "C-h F") #'helpful-function))))
#+END_SRC

Use which-key to display the key bindings following your currently entered incomplete command (a prefix) in a popup
#+begin_src emacs-lisp
(use-package which-key
  :delight
  :init (which-key-mode)
  :config
  (setq which-key-idle-delay 0.3))
#+end_src

** Scratch Buffer

Configure persistent-scratch to restore on startup, save on exit, autosave every 2 minutes.

#+begin_src emacs-lisp
(use-package persistent-scratch
  :ensure t
  :init
  ;; Paths
  (setq persistent-scratch-save-file
        (expand-file-name "persistent-scratch.el" user-emacs-directory))
  (setq persistent-scratch-backup-directory
        (expand-file-name "persistent-scratch/" user-emacs-directory))

  ;; Ensure backup dir exists
  (unless (file-directory-p persistent-scratch-backup-directory)
    (make-directory persistent-scratch-backup-directory t))

  ;; Autosave every 2 minutes (default is 30s)
  (setq persistent-scratch-autosave-interval 120)

  :config
  ;; Restore on startup, save on exit
  (persistent-scratch-setup-default)

  ;; Periodic autosave timer
  (persistent-scratch-autosave-mode 1))
#+end_src

** User Interface

Display the cursor's column number
#+BEGIN_SRC emacs-lisp
(setq column-number-mode t)
#+END_SRC

Display the buffer size
#+BEGIN_SRC emacs-lisp
(setq size-indication-mode t)
#+END_SRC

Enable mouse scroller on vertical scroll bar
#+BEGIN_SRC emacs-lisp
(global-set-key [vertical-scroll-bar mouse-4] 'scroll-down)
(global-set-key [vertical-scroll-bar mouse-5] 'scroll-up)
#+END_SRC

Enable mouse scroller in active window
#+BEGIN_SRC emacs-lisp
(global-set-key [mouse-4] 'scroll-down)
(global-set-key [mouse-5] 'scroll-up)
#+END_SRC

Enable wheelmouse support
#+BEGIN_SRC emacs-lisp
(cond (window-system
       (mwheel-install)
))
#+END_SRC

Set the default fonts
#+BEGIN_SRC emacs-lisp
(set-face-attribute 'default nil :height 180)

;; On "OS X", set the default font to "Monaco 18"
(when (equal system-type 'darwin)
  (set-face-attribute 'default nil :font "Monaco 18")
  )
#+END_SRC

Window configuration
#+BEGIN_SRC emacs-lisp
(when window-system
  (mouse-wheel-mode t)    ; enable mouse wheel support
  (setq frame-title-format '(buffer-file-name "%f" ("%b")))
  (tooltip-mode t)        ; show tooltips
  (tool-bar-mode -1)      ; don't show the toolbar
  (blink-cursor-mode -1)  ; don't blink the cursor
  )
#+END_SRC

Don't underline highlighted text
#+BEGIN_SRC emacs-lisp
(set-face-attribute 'highlight nil :underline nil)
#+END_SRC

Use spaceline, the package that provides Spacemacs with its mode-line theme.
#+begin_src emacs-lisp
(use-package spaceline
  :ensure t
  :init
  (require 'spaceline-config)
  (spaceline-spacemacs-theme))
#+end_src

#+BEGIN_SRC emacs-lisp
(use-package emacs
  :delight
  (global-whitespace-mode)
  (visual-line-mode)
  (whole-line-or-region-mode)
)
#+END_SRC

** Key Bindings

#+BEGIN_SRC emacs-lisp
(global-set-key (kbd "<f1>") (lambda () (interactive) (dired (expand-file-name "~/docs/*org")) (revert-buffer)))
(global-set-key (kbd "<f2>") 'query-replace)
(global-set-key (kbd "<f4>") 'projectile-ag)
(global-set-key (kbd "<f5>") 'revert-buffer-no-confirm)
(global-set-key (kbd "<f8>") 'projectile-find-file)
(global-set-key (kbd "<f9>") 'eval-region)
#+END_SRC

Rebind "expand-region"
http://endlessparentheses.com/where-do-you-bind-expand-region-.html?source=rss
#+BEGIN_SRC emacs-lisp
(use-package expand-region
  :bind ("C-=" . er/expand-region))
#+END_SRC

A function that simply duplicates the current line, bound to F12
#+BEGIN_SRC emacs-lisp
(defun duplicate-line()
  (interactive)
  (move-beginning-of-line 1)
  (kill-line)
  (yank)
  (open-line 1)
  (next-line 1)
  (yank)
)
(global-set-key (quote [f12]) 'duplicate-line)
#+END_SRC

** Backups

backup file management
#+BEGIN_SRC emacs-lisp
(defvar backup-dir (expand-file-name ".backups" user-emacs-directory))

(setq
 backup-by-copying t      ; don't clobber symlinks
 backup-directory-alist (list (cons "." backup-dir))
 delete-old-versions t
 kept-new-versions 6
 kept-old-versions 2
 version-control t)       ; use versioned backups
#+END_SRC

** Buffers

*** General

Uniquify changes conflicting buffer names from file<2> etc
#+BEGIN_SRC emacs-lisp
(use-package uniquify
   :ensure nil
   :config
   (setq uniquify-buffer-name-style 'forward)
   (setq uniquify-separator "/")
   ;; Rename after killing uniquified
   (setq uniquify-after-kill-buffer-p t)
   ;; Don't muck with special buffers
   (setq uniquify-ignore-buffers-re "^\\*"))
#+END_SRC

By default sort the buffer list by column 'Mode'
#+BEGIN_SRC emacs-lisp
(setq Buffer-menu-sort-column 4)
#+END_SRC

Focus the buffer window when listing the buffers
#+BEGIN_SRC emacs-lisp
(define-key global-map [remap list-buffers] 'buffer-menu-other-window)
#+END_SRC

*** Ibuffer

Use Ibuffer for buffer list
#+BEGIN_SRC emacs-lisp
(global-set-key (kbd "C-x C-b") 'ibuffer)
#+END_SRC

Create custom Ibuffer groups
#+BEGIN_SRC emacs-lisp
(setq ibuffer-saved-filter-groups
      '(("home"
         ("Org" (or (mode . org-mode)
                    (filename . "OrgMode")))
         ("Web" (or (mode . web-mode)
                    (name . ".css")))
         ("Python" (or (mode . python-mode)
                       (filename . "LaTeXMode")))
         ("Helm" (name . "helm"))
         ("Dired" (mode . dired-mode))
         ("Elisp" (mode . emacs-lisp-mode))
         ("Magit" (name . "magit"))
         ("Emacs" (or
                   (name . "^\\*scratch\\*$")
                   (name . "^\\*Messages\\*$")))
         ("Text" (or (name . ".txt")
                     (name . ".md")
                     (name . ".xml"))))))

(add-hook 'ibuffer-mode-hook
    '(lambda ()
        (ibuffer-switch-to-saved-filter-groups "home")))
#+END_SRC

Customize the column widths
#+BEGIN_SRC emacs-lisp
(setq ibuffer-formats
      '((mark modified read-only " "
              (name 30 30 :left :elide) ; change: 30s were originally 18s
              " "
              (size 9 -1 :right)
              " "
              (mode 16 16 :left :elide)
              " " filename-and-process)
        (mark " "
              (name 16 -1)
              " " filename)))
#+END_SRC

Enabling this lets you delete buffers without confirmation
#+BEGIN_SRC emacs-lisp
(setq ibuffer-expert t)
#+END_SRC

** Sessions

save my place in files between sessions
#+BEGIN_SRC emacs-lisp
(use-package saveplace
  :config
  (setq save-place-file (expand-file-name ".saveplaces" user-emacs-directory))
  ;; activate it for all buffers
  (setq-default save-place t)
)
#+END_SRC

Automatically save and restore sessions
#+BEGIN_SRC emacs-lisp
(desktop-save-mode t)
;; Only restore 5 buffers immediately to improve startup-time. The
;;  others are lazily restored when Emacs is idle.
(setq desktop-restore-eager 5)
#+END_SRC

Use the Session package to save registers, which I use to store
frame and window configuration. State is saved in ~/.emacs.d/session.
#+begin_src emacs-lisp
(use-package session
  :config
  (session-initialize))
#+end_src

Store the session file here
#+BEGIN_SRC emacs-lisp
(setq desktop-dirname "~/.emacs.d/")
(setq desktop-path (list desktop-dirname))
#+END_SRC

Save mini-buffer history between sessions
#+BEGIN_SRC emacs-lisp
(setq savehist-additional-variables        ;; also save...
  '(search-ring regexp-search-ring)    ;; ... my search entries
  savehist-file "~/.emacs.d/savehist") ;; keep my home clean
(savehist-mode t)                          ;; do customization before activate
#+END_SRC
** Typing and Spelling

Use abbrev mode to correct often misspelled words
#+BEGIN_SRC emacs-lisp
(use-package abbrev
  :defer 1
  :ensure nil
  :custom
  (abbrev-file-name (expand-file-name "abbrev_defs" user-emacs-directory))
  (abbrev-mode 1)
  :config
  (if (file-exists-p abbrev-file-name)
      (quietly-read-abbrev-file))
  :delight)
#+END_SRC

Use the YASnippet template system
#+BEGIN_SRC emacs-lisp
(use-package yasnippet
  :delight yas-minor-mode
  :ensure t
  :config
  (setq
   yas-verbosity 1
   yas-wrap-around-region t)

  (yas-reload-all)
  (yas-global-mode)

  ;; make any snippets in the "fundamental-mode" subdirectory available in any mode
  (add-hook 'yas-minor-mode-hook (lambda () (yas-activate-extra-mode 'fundamental-mode))))
#+END_SRC

** File Editing
*** Tramp

Decrease tramp's verbosity level
#+BEGIN_SRC emacs-lisp
(setq tramp-verbose 2)
#+END_SRC

*** Filling Paragraphs

Change the maximum line width for filling
#+begin_src emacs-lisp
(setq fill-column 80)
#+end_src

Add an "unfill" function that is the opposite of fill-paragraph
#+begin_src emacs-lisp
(defun unfill-paragraph ()
  "Takes a multi-line paragraph and makes it into a single line of text."
  (interactive)
  (let ((fill-column (point-max)))
    (fill-paragraph nil)))
#+end_src

** Window Management

;; make new frames start maximized
#+begin_src emacs-lisp
(add-to-list 'default-frame-alist '(fullscreen . maximized))
#+end_src

#+BEGIN_SRC emacs-lisp
(defun switch-registers()
  (interactive)
  (read-char "Switch to register: ")
  ;; Save the current state of all frames and windows to current register,
  ;;  which is saved in a custom variable.
  (if (boundp 'saved-register)
      (frameset-to-register saved-register))
  ;; Save the current register to custom variable
  (setq saved-register last-input-event)
  ;; Jump to specified register
  (jump-to-register last-input-event)
  )
(global-set-key (quote [f6]) 'switch-registers)
#+END_SRC

* Navigation
** General

The <home> and <end> keys should move to the beginning and end of the buffer, respectively
#+BEGIN_SRC emacs-lisp
(global-set-key [home] 'beginning-of-buffer)
(global-set-key [end] 'end-of-buffer)
#+END_SRC

Window navigation
#+BEGIN_SRC emacs-lisp
(global-set-key (kbd "C-x <left>") 'windmove-left)
(global-set-key (kbd "C-x <right>") 'windmove-right)
(global-set-key (kbd "C-x <up>") 'windmove-up)
(global-set-key (kbd "C-x <down>") 'windmove-down)
#+END_SRC

create a list of recently opened files
#+BEGIN_SRC emacs-lisp
(use-package recentf
  :config
  (recentf-mode 1))
#+END_SRC

Auto refresh buffers, but be quiet about it
#+BEGIN_SRC emacs-lisp
(use-package autorevert
  :delight auto-revert-mode
  :config
  (setq global-auto-revert-non-file-buffers t)
  (setq auto-revert-verbose nil))
#+END_SRC
** Completions

Use ivy for file and buffer completions
#+begin_src emacs-lisp
  (use-package ivy
    :delight
    :bind
    (("C-s" . swiper)
     ("C-r" . swiper))
    :bind
    (:map ivy-minibuffer-map
     ;; I'm accustomed to Helm's C-l key binding when moving
     ;;  up a directory while navigating files
     ("C-l" . ivy-backward-delete-char)
     ("RET" . ivy-alt-done))
    :init
    (ivy-mode 1)
    :config
    ;; Add recent files and bookmarks to the ivy-switch-buffer
    (setq ivy-use-virtual-buffers t)
    (setq ivy-count-format "(%d/%d) ")

    ;; Set this to avoid performance problems when editing large
    ;;  buffers in Visual Line Mode
    (setq swiper-use-visual-line-p #'ignore)

    (global-set-key (kbd "M-x") 'counsel-M-x)
    (global-set-key (kbd "C-x C-f") 'counsel-find-file)
    (global-set-key (kbd "C-h f") 'counsel-describe-function)
    (global-set-key (kbd "C-h v") 'counsel-describe-variable))
#+end_src

#+begin_src emacs-lisp
  (use-package all-the-icons-ivy-rich
    :ensure t
    :init (all-the-icons-ivy-rich-mode 1))
#+end_src

#+begin_src emacs-lisp
  (use-package ivy-rich
    :init
    (ivy-rich-mode 1)
    :after ivy
    :hook (ivy-mode . ivy-rich-mode)
    :custom (ivy-rich-path-style 'abbrev)
    :config
    (ivy-rich-modify-columns
     'ivy-switch-buffer
     '((ivy-rich-candidate (:width 30))
       (ivy-rich-switch-buffer-size (:align right))
       (ivy-rich-switch-buffer-indicators (:width 4 :face error :align right))
       (ivy-rich-switch-buffer-major-mode (:width 20 :face error))
       (ivy-rich-switch-buffer-project (:width 20 :face success))
       (ivy-rich-switch-buffer-path (:width (lambda (x) (ivy-rich-switch-buffer-shorten-path x (ivy-rich-minibuffer-width 0.3))))))))
#+end_src

#+begin_src emacs-lisp
(use-package company
  :defer 0.1
  :delight
  :custom
  (company-minimum-prefix-length 2)
  (company-idle-delay 0.01)
  :config
  (setq-default
   company-idle-delay 0.05
   company-require-match nil
   company-minimum-prefix-length 0

   ;; get only preview
   company-frontends '(company-preview-frontend)
   ;; Display a drop down
   company-frontends '(company-pseudo-tooltip-frontend company-preview-frontend)
   ))
#+end_src

#+begin_src emacs-lisp
(use-package company-box
  :delight
  :hook (company-mode . company-box-mode))
#+end_src

** Imenu

Automatically use Imenu, as needed
#+BEGIN_SRC emacs-lisp
  (add-hook 'org-mode-hook
            (lambda () (imenu-add-to-menubar "Org Nodes")))

  ;; Disable this to improve performance in large documents
  (setq org-imenu-depth 0)
#+END_SRC

Imenu: display 50 items in each submenu
#+BEGIN_SRC emacs-lisp
(setq imenu-max-items 50)
#+END_SRC

Imenu: sort functions alphabetically
#+BEGIN_SRC emacs-lisp
(setq imenu-sort-function 'imenu--sort-by-name)
#+END_SRC

Rescan the buffer automatically for new functions
#+BEGIN_SRC emacs-lisp
(setq imenu-auto-rescan t)
#+END_SRC

** Projectile

#+BEGIN_SRC emacs-lisp
  (use-package projectile
    :delight
    :ensure t
    :config
    (define-key projectile-mode-map (kbd "C-c p") 'projectile-command-map)
    (projectile-mode +1))
#+END_SRC

Define the list of directories that counsel-projectile-ag should ignore
#+begin_src emacs-lisp
  (defun projectile-ignored-directories-rel ()
    "Return list of ignored directories, relative to the root."
    '("htmlcov" "bordercore/static")
    )
#+end_src

Use Ivy/counsel when running projectile commands, eg ~counsel-projectile-ag~
instead of ~projectile-ag~ when searching a project.
#+begin_src emacs-lisp
  (use-package counsel-projectile
    :after projectile
    :ensure t
    :config
    (counsel-projectile-mode))
#+end_src

** Search
*** The Silver Searcher

ag.el is a frontend to the Silver Searcher.
This requires installation of the "ag" binary.
#+BEGIN_SRC emacs-lisp
(use-package ag
  :commands ag
  :init
  (setq ag-highlight-search t)
  :config
  ;; Focus the search buffer after a search
  (add-hook 'ag-search-finished-hook (lambda () (pop-to-buffer next-error-last-buffer))))
#+END_SRC
** Treemacs

#+BEGIN_SRC emacs-lisp
(use-package treemacs
  :ensure t
  :defer t
  :init
  :config
  (progn
    (setq treemacs-collapse-dirs                 (if treemacs-python-executable 3 0)
          treemacs-deferred-git-apply-delay      0.5))

  (treemacs-follow-mode nil)
    :bind
      (:map global-map
        ([f7] . treemacs))
)

(use-package treemacs-magit
  :after treemacs magit
  :ensure t)
#+END_SRC
* Dired

#+begin_src emacs-lisp
  (use-package dired
  :ensure nil
  :config
  (define-key dired-mode-map "H" 'dired-omit-mode)
  )
#+end_src

#+RESULTS:
: t

#+BEGIN_SRC emacs-lisp
(use-package diredfl
  :ensure t
  :config
  ;; Don't disable "dired-find-alternate-file"
  (put 'dired-find-alternate-file 'disabled nil)
  ;; Hilight the current line in dired mode
  (add-hook 'dired-mode-hook 'hl-line-mode))
#+END_SRC
* Org Mode

#+BEGIN_SRC emacs-lisp
(use-package org
  :ensure org-plus-contrib
  :config
  ;; Turn on org-indent-mode for all files
  (setq org-startup-indented t)
  ;; Don't insert blank lines before new entries/items
  (setq org-blank-before-new-entry '((heading . nil) (plain-list-item . nil)))
  ;; Hit <RETURN> to follow the link at point
  (setq org-return-follows-link t)
  ;; By default, the return key inserts a new heading
  ;; (add-hook 'org-mode-hook
  ;; (lambda ()
  ;;   (define-key org-mode-map (kbd "RET") 'org-insert-heading-respect-content)))
  ;; Add an intermediate 'IN PROGRESS' todo state
  (setq org-todo-keywords '((sequence "TODO" "IN PROGRESS" "|" "DONE")))
  ;; TODO statistics covers all entries in the subtree, not just direct children
  (setq org-hierarchical-todo-statistics nil)

  ;; Disable indentation of code blocks. The default is 2.
  (setq org-edit-src-content-indentation 0)

  ;; With this set, hitting 's' at the beginning of a headline will narrow to the
  ;;  current subtree. Hitting 's' again will unnarrow the buffer.
  (setq org-use-speed-commands t)

  ;; Fold all content on startup
  (setq org-startup-folded t)

  ;; Babel Mode
  ;; Some initial languages we want org-babel to support
  (org-babel-do-load-languages 'org-babel-load-languages
                               '((shell . t)
                                 (emacs-lisp . t)
                                 (python . t)
                                 (R . t)
                                 (ruby . t)
                                 (ditaa . t)
                                 (dot . t)
                                 (octave . t)
                                 (sql . t)
                                 (sqlite . t)
                                 (perl . t)
                                 (php . t)))
  ;; Use bash (rather than the default sh) as the command to invoke a shell
  (setq org-babel-sh-command "bash")
  ;; Turn on native code fontification
  (setq org-src-fontify-natively t)
  ;; Don't confirm before evaluating code
  (setq org-confirm-babel-evaluate nil)

  ;; Capture Mode
  ;; Set notes file and key binding
  (setq org-default-notes-file (concat "~/Dropbox/life.org"))
  (define-key global-map "\C-cc" 'org-capture)

  ;; Customize the faces. I prefer the font sizes to be consistent across levels
  (set-face-attribute 'org-level-1 nil :height 1.0)
  (set-face-attribute 'org-level-2 nil :height 1.0)
  (set-face-attribute 'org-level-3 nil :height 1.0)
  (set-face-attribute 'org-level-4 nil :height 1.0)
  (set-face-attribute 'org-level-5 nil :height 1.0)
  (set-face-attribute 'org-level-6 nil :height 1.0)
  (set-face-attribute 'org-level-7 nil :height 1.0)
  (set-face-attribute 'org-level-8 nil :height 1.0)

  ;; Make list markers a little more visually appealing
  (font-lock-add-keywords 'org-mode
                          '(("^ *\\([-]\\) "
                             (0 (prog1 () (compose-region (match-beginning 1) (match-end 1) "•"))))))

  ;; Hide the emphasis markers in *bold* and /italics/
  (setq org-hide-emphasis-markers t)

  ;; TABs in code blocks should act as if they were issued in the language major mode buffer
  (setq org-src-tab-acts-natively t)
)
#+END_SRC

Include a Table of Contents, primarily for the benefit of Github.
The TOC automatically gets updated when the buffer is saved under the heading with the "TOC" tag.
#+BEGIN_SRC emacs-lisp
(use-package toc-org
  :hook
  (org-mode . toc-org-mode))
#+END_SRC

#+BEGIN_SRC emacs-lisp
(use-package org-contacts
  :ensure nil
  :after org)
#+END_SRC

#+BEGIN_SRC emacs-lisp
(use-package org-capture
  :ensure nil
  :after org
  :preface
  (defvar my/org-contacts-template "* %(org-contacts-template-name)
:PROPERTIES:
:ADDRESS: %^{Address}
:BIRTHDAY: %^{Birthday (yyyy-mm-dd)}
:EMAIL: %(org-contacts-template-email)
:HOME_PHONE: %^{Home Phone}
:WORK_PHONE: %^{Work Phone}
:URL: %^{Url}
:NOTE: %^{Note}
:END:" "Template for org-contacts.")
  :custom
  (org-capture-templates
      `(("c" "Contact" entry (file+headline "~/docs/personal/contacts.org" "Contacts"),
      my/org-contacts-template
     :empty-lines 0)
  ("t" "Todo" entry (file+headline org-default-notes-file "Tasks")
  "* TODO %?  %t  %^g"))))
#+END_SRC

Define a function which toggles the return key binding between
'org-return' and 'org-insert-respect-content'
#+BEGIN_SRC emacs-lisp
(defun toggle-org-return-key ()
  (interactive)
  (if (string= (key-binding (kbd "RET")) "org-return")
    (define-key org-mode-map (kbd "RET") 'org-insert-heading-respect-content)
    (define-key org-mode-map (kbd "RET") 'org-return))
  )
#+END_SRC

#+BEGIN_SRC emacs-lisp
(use-package org-expiry
  :ensure org-plus-contrib
  :config
  (setq
    org-expiry-created-property-name "CREATED" ; Name of property when an item is created
    org-expiry-inactive-timestamps   t         ; Don't have everything in the agenda view
  ))
#+END_SRC

Disable displaying the outline path in the echo area
#+BEGIN_SRC emacs-lisp
(remove-hook 'org-mode-hook 'org-eldoc-load)
#+END_SRC

Use org-cliplink to insert org-mode links from clipboard.
Bind to F3.
#+BEGIN_SRC emacs-lisp
(use-package org-cliplink
  :config
  (global-set-key (quote [f3]) 'org-cliplink))
#+END_SRC

org-refile settings
https://blog.aaronbieber.com/2017/03/19/organizing-notes-with-refile.html
#+begin_src emacs-lisp

;; defines the possible targets
(setq org-refile-targets '((nil :maxlevel . 5)
                           (org-agenda-files :maxlevel . 5)))

;; better interoperate with Helm
(setq org-outline-path-complete-in-steps nil)
(setq org-refile-use-outline-path t)

#+end_src

Use Github Flavored Markdown exporter for Org Mode
#+begin_src elisp
  (with-eval-after-load "org"
    (require 'ox-gfm nil t))
#+end_src

I add this hook at the top of most org-mode files that are
destined for export to Bordercore. Mark this variable and value
as safe to avoid a "apply unsafe local variable" warning.

#+begin_src elisp
(add-to-list 'safe-local-variable-values
  '(after-save-hook . org-gfm-export-to-markdown))
#+end_src

Diminish org-indent mode

#+begin_src elisp
(with-eval-after-load 'org-indent
  (require 'diminish)
  (diminish 'org-indent-mode))
#+end_src

** Todo items
#+BEGIN_SRC emacs-lisp
(defun org-summary-todo (n-done n-not-done)
  "Switch entry to DONE when all subentries are done, to TODO otherwise."
  (let (org-log-done org-log-states)   ; turn off logging
  (org-todo (if (= n-not-done 0) "DONE" "TODO"))))

(add-hook 'org-after-todo-statistics-hook 'org-summary-todo)
#+END_SRC

#+begin_src emacs-lisp
(defun mrb/insert-created-timestamp()
  "Insert a CREATED property using org-expiry.el for TODO entries"
  (org-expiry-insert-created)
  (org-back-to-heading)
  (org-end-of-line)
)
#+end_src

Whenever a TODO entry is created, add a timestamp. [[https://stackoverflow.com/questions/12262220/add-created-date-property-to-todos-in-org-mode][Source]]

#+begin_src emacs-lisp
(defadvice org-todo (after mrb/created-timestamp-advice activate)
  "Insert a CREATED property using org-expiry.el for TODO entries"
  (mrb/insert-created-timestamp)
)
#+end_src

Make it active

#+begin_src emacs-lisp
(ad-activate 'org-todo)
#+end_src
this is text
** Auto-show Emphasis Markers

This package makes it much easier to edit Org documents when ~org-hide-emphasis-markers~ is enabled. It temporarily shows the emphasis markers around certain markup elements when you place your cursor inside of them.

#+begin_src emacs-lisp
(use-package org-appear
  :hook (org-mode . org-appear-mode))
#+end_src
** Eye Candy

Show org-mode bullets and ellipses as UTF-8 characters

#+BEGIN_SRC emacs-lisp
(use-package org-bullets
  :init
  (setq org-ellipsis " ⬎")
  (set-face-attribute 'org-ellipsis nil :underline nil)
  (add-hook 'org-mode-hook (lambda () (org-bullets-mode 1))))
#+END_SRC

Show org priorities as custom strings

#+BEGIN_SRC emacs-lisp
(use-package org-fancy-priorities
  :delight
  :ensure t
  :hook
  (org-mode . org-fancy-priorities-mode)
  :config
  (setq org-fancy-priorities-list '("MED", "HIGH", "LOW")))
#+END_SRC

* Development
** Misc

hilight matching pairs of parentheses and other characters
#+BEGIN_SRC emacs-lisp
(show-paren-mode t)
#+END_SRC

C support
#+BEGIN_SRC emacs-lisp
(add-hook 'c-mode-common-hook
  (lambda ()
    (c-set-style "k&r")
    (setq c-basic-offset 4)))
#+END_SRC

Perl support
cperl-mode indentation offset
#+BEGIN_SRC emacs-lisp
(setq cperl-indent-level 4)
#+END_SRC

#+BEGIN_SRC emacs-lisp
(add-to-list 'auto-mode-alist '("\\.pl\\'" . cperl-mode))
(add-to-list 'auto-mode-alist '("\\.pm\\'" . cperl-mode))
#+END_SRC

for re-builder mode, set the syntax to 'string' to avoid extra escaping
#+BEGIN_SRC emacs-lisp
(setq reb-re-syntax 'string)
#+END_SRC

Hilight Postgres keywords in SQL mode
#+BEGIN_SRC emacs-lisp
(add-hook 'sql-mode-hook
          (lambda ()
            (sql-highlight-postgres-keywords)))
#+END_SRC

Enable json-mode when editing JSON files
#+BEGIN_SRC emacs-lisp
  (use-package json-mode
    :mode ("\\.json" . json-mode))
#+END_SRC
** Language Server Protocol (LSP)

#+begin_src emacs-lisp
(use-package lsp-mode
  :delight
  :commands lsp
  :hook ((typescript-mode js2-mode web-mode) . lsp)
  :config
  (setq lsp-enable-file-watchers nil)

  ;; Configure LSP to use flycheck for linting
  (setq lsp-diagnostics-provider :flycheck)

  ;; Tell ESLint LSP to treat "bordercore" (relative to the workspace) as the package root for resolving config/plugins.
  (setq lsp-eslint-working-directories '("bordercore"))

  :custom
  (lsp-headerline-breadcrumb-enable t)

  (lsp-headerline-breadcrumb-segments '(project file symbols)))
#+end_src

Use pyright as the LSP Python server.

#+begin_src emacs-lisp
(use-package lsp-pyright
  :hook
  (python-mode . (lambda ()
                   (require 'lsp-pyright)
                   (lsp-deferred))))
#+end_src

#+begin_src emacs-lisp
(use-package lsp-ui
  :hook (lsp-mode . lsp-ui-mode)
  :config
  (setq lsp-ui-sideline-enable nil)
  (setq lsp-ui-sideline-show-diagnostics nil)
  (setq lsp-ui-doc-show-with-cursor t)
  (setq lsp-ui-doc-position 'top)
  )
#+end_src

#+begin_src emacs-lisp
(use-package lsp-ivy
  :after lsp-mode
  )
#+end_src

** Python

Set PYTHONPATH so that pylint will properly read the django-settings-module config option inside .pylintrc for Django linting
#+begin_src emacs-lisp
(let ((existing (getenv "PYTHONPATH")))
  (setenv "PYTHONPATH"
          (mapconcat 'identity
                     (delete-dups (append (split-string (or existing "") ":")
                                          '("/home/jerrell/dev/django/bordercore" "/home/jerrell/dev/django/bordercore/bordercore")))
                     ":")))
#+end_src

Use flycheck for on-the-fly syntax checking
#+BEGIN_SRC emacs-lisp
(use-package flycheck
  :delight
  :ensure t
  :config
  ;; Tell flycheck to use eslint when in web-mode
  (flycheck-add-mode 'javascript-eslint 'web-mode)
  :init (global-flycheck-mode))
#+END_SRC

Display flycheck error messages via posframe, which pops up a frame at point to show diagnostics without inserting text into the buffer or disrupting code layout.
#+BEGIN_SRC emacs-lisp
(use-package flycheck-posframe
  :after flycheck
  :config
  (custom-set-faces
   ;; Background of the popup
   '(flycheck-posframe-background-face ((t (:background "#1c1f26"))))
   ;; Error text
   '(flycheck-posframe-face ((t (:foreground "red" :weight bold))))
   ;; Warning test
   '(flycheck-posframe-warning-face ((t (:foreground "cyan"))))
   ;; Info text
   '(flycheck-posframe-info-face ((t (:foreground "DeepSkyBlue1"))))
   ;; Border text -- not working
   '(flycheck-posframe-border-face ((t (:foreground "gray60"))))
   )
  (setq flycheck-posframe-border-width 20)
  (add-hook 'flycheck-mode-hook #'flycheck-posframe-mode))
#+END_SRC

Add any directory-local variables found in bc/trusted-project-paths (found in locals.e) to the trusted project path. Typically used for setting ~flycheck-python-pylint-executable~ on a per-project basis.
#+begin_src emacs-lisp
(defun bc/within-trusted-project-p (dir)
  "Return non-nil if DIR is inside one of `bc/trusted-project-paths`."
  (let ((dir (file-truename (expand-file-name dir))))
    (cl-some (lambda (trusted)
               (string-prefix-p (file-truename (expand-file-name trusted)) dir))
             bc/trusted-project-paths)))

(defun bc/trust-dir-locals ()
  "Mark all directory-local variables as safe if in a trusted project path."
  (let ((dir (file-truename (or buffer-file-name default-directory))))
    (when (bc/within-trusted-project-p dir)
      (let ((inhibit-message t))
        (hack-local-variables)
        (dolist (pair (buffer-local-variables))
          (let ((sym (car pair))
                (val (cdr pair)))
            (when (and (not (memq sym '(nil t)))
                       (not (safe-local-variable-p sym val)))
              (add-to-list 'safe-local-variable-values (cons sym val)))))))))

(add-hook 'python-mode-hook #'bc/trust-dir-locals)
#+end_src

Use isort to automatically sort Python imports on save.
To install isort: sudo apt install isort python3-isort

#+BEGIN_SRC emacs-lisp
(use-package py-isort
  :config
  (add-hook 'before-save-hook 'py-isort-before-save))
#+END_SRC

Set the default tab width to 4
#+BEGIN_SRC emacs-lisp
(setq-default tab-width 4)
#+END_SRC

Don't use tabs for indentation
#+BEGIN_SRC emacs-lisp
(setq-default indent-tabs-mode nil)
#+END_SRC

Use pyvenv to manage virtual environments.
Useful in dap-mode.
#+begin_src emacs-lisp
(use-package pyvenv
  :ensure t)
#+end_src

Use dap-mode for Python debugging
#+begin_src emacs-lisp
(use-package dap-mode
  :ensure t
  :config
  (require 'dap-python)
  (setq dap-auto-configure-features '(sessions locals controls tooltip))
  (dap-auto-configure-mode 1)
  ;; Bring up a hydra automatically when a breakpoint is hit
  :hook
  (dap-stopped .(lambda (arg) (call-interactively #'dap-hydra)))
  )
#+end_src

** Web Development

I use web-mode for Django and Vue.js development
#+BEGIN_SRC emacs-lisp
(use-package web-mode
  :init
  (add-to-list 'auto-mode-alist '("\\.html?\\'" . web-mode))
  (add-to-list 'auto-mode-alist '("\\.vue\\'" . web-mode))

  ;; These two functions remove screen artifacts when you change the
  ;;  indentation using both web-mode and highlight-indent-guides mode.
  ;;  https://github.com/DarthFennec/highlight-indent-guides/issues/22
  (defun my-unfontify-function (beg end)
    (remove-list-of-text-properties beg end '(display)))
  (defun my-register-unfontify ()
    (setq font-lock-unfontify-region-function 'my-unfontify-function))
  (add-hook 'web-mode-hook 'my-register-unfontify t)
  :config
  (setq web-mode-engines-alist
        '(("django"    . "\\.html\\'")))
  (setq web-mode-markup-indent-offset 4)
  (setq web-mode-css-indent-offset 4)
  (setq web-mode-code-indent-offset 4)

  ;; Disable erroneous auto-formatting after yanking text
  (setq web-mode-enable-auto-indentation nil)

  (setq web-mode-indent-style 4)
  (setq web-mode-style-padding 4)
  (setq web-mode-script-padding 4)
  (setq web-mode-enable-css-colorization t))
#+END_SRC

Use highlight-indent-guides mode to display indentation levels
#+begin_src emacs-lisp
(use-package highlight-indent-guides
  :delight
  :config

  ;; Use the 'character' display method
  (setq highlight-indent-guides-method 'character)

  ;; Use different colors for odd and even indentation levels
  ;; https://github.com/DarthFennec/highlight-indent-guides/issues/64
  (defface my-highlighter-even-face '((t :foreground "#292929")) "")
  (defface my-highlighter-odd-face '((t :foreground "#191919")) "")

  (defun my-highlighter (level responsive display)
    (if (cl-evenp level)
      'my-highlighter-even-face
      'my-highlighter-odd-face))

  (setq highlight-indent-guides-highlighter-function 'my-highlighter)

  ;; Use this mode when in web-mode
  (add-hook 'prog-mode-hook 'highlight-indent-guides-mode)
  )
#+end_src

Use Rainbow minor mode when in CSS mode
#+BEGIN_SRC emacs-lisp
(add-hook 'css-mode-hook 'rainbow-mode)
#+END_SRC

Use C-Style indentation in CSS mode
#+BEGIN_SRC emacs-lisp
(setq cssm-indent-function #'cssm-c-style-indenter)
#+END_SRC

Change the size of one indentation step
#+begin_src emacs-lisp
(setq css-indent-offset 2)
#+end_src
** Productivity

Enable rainbow-delimiters in most programming modes

#+begin_src emacs-lisp
(add-hook 'prog-mode-hook #'rainbow-delimiters-mode)
#+end_src

** Lisp

Add more keywords for font-lock hilighlighting
#+BEGIN_SRC emacs-lisp
(font-lock-add-keywords 'lisp-mode
  '(("\\<\\(add-hook\\|setq\\|autoload\\|add-to-list\\|setq-default\\)\\>" . font-lock-keyword-face)))
#+END_SRC

If the matching paren is offscreen, show the matching line in the echo area
See http://www.emacswiki.org/emacs/ShowParenMode
#+BEGIN_SRC emacs-lisp
(defadvice show-paren-function
      (after show-matching-paren-offscreen activate)
      "If the matching paren is offscreen, show the matching line in the
        echo area. Has no effect if the character before point is not of
        the syntax class ')'."
      (interactive)
      (let* ((cb (char-before (point)))
             (matching-text (and cb
                                 (char-equal (char-syntax cb) ?\) )
                                 (blink-matching-open))))
        (when matching-text (message matching-text))))
#+END_SRC

** Magit

support for Magit, which provides nice Git integration with Emacs
#+BEGIN_SRC emacs-lisp
(use-package magit
    :init
    (setq magit-log-margin '(t "%b %d, %Y " magit-log-margin-width t 21))
)
#+END_SRC

Custom key binding for the often-used "magit-status" command
#+BEGIN_SRC emacs-lisp
(global-set-key (kbd "C-x g") 'magit-status)
#+END_SRC

full screen magit-status
http://whattheemacsd.com/setup-magit.el-01.html
#+BEGIN_SRC emacs-lisp
(defadvice magit-status (around magit-fullscreen activate)
  (window-configuration-to-register :magit-fullscreen)
  ad-do-it
  (delete-other-windows))
#+END_SRC

#+BEGIN_SRC emacs-lisp
(defun magit-quit-session ()
  "Restores the previous window configuration and kills the magit buffer"
  (interactive)
  (kill-buffer)
  (jump-to-register :magit-fullscreen))

(define-key magit-status-mode-map (kbd "q") 'magit-quit-session)
#+END_SRC

Remove the 'Recent Commits' section from the Magit status buffer
#+BEGIN_SRC emacs-lisp
(magit-add-section-hook 'magit-status-sections-hook
                        'magit-insert-unpushed-to-upstream
                        'magit-insert-unpushed-to-upstream-or-recent
                        'replace)
#+END_SRC

Automatically display the process buffer on error
#+BEGIN_SRC emacs-lisp
(defun auto-display-magit-process-buffer (&rest args)
  "Automatically display the process buffer on error."
  (let ((magit-display-buffer-noselect t))
    (magit-process-buffer)))

(advice-add 'magit-process-set-mode-line-error-status :before
            #'auto-display-magit-process-buffer)
#+END_SRC

#+BEGIN_SRC emacs-lisp
(defun magit-status-font-setup ()
  "Set a specific font size for the Magit status buffer."
  (when (derived-mode-p 'magit-status-mode)
    (buffer-face-set '(:height 280))))

(add-hook 'magit-status-mode-hook 'magit-status-font-setup)
#+END_SRC

** diff-hl

#+BEGIN_SRC emacs-lisp
(use-package diff-hl
  :ensure t
  :init
  (global-diff-hl-mode)
)
#+END_SRC

** YAML

#+BEGIN_SRC emacs-lisp
(use-package yaml-mode
  :mode (("\\.yaml\\'" . yaml-mode)
         ("\\.yml\\'"       . yaml-mode)))
#+END_SRC
* AI
** ChatGPT

chatgpt-shell provides shell support to ChatGPT and Dall-E.
Add your OpenAI key to ~/.netrc.

#+begin_src emacs-lisp
(use-package chatgpt-shell
  :ensure t
  :config
  (setq chatgpt-shell-openai-key
        (auth-source-pick-first-password :host "api.openai.com"))
  (setq chatgpt-shell-model-version "gpt-4.1")
  )
#+end_src

Bind C-c s to check the current paragraph for spelling and grammar
Snippet source: https://www.reddit.com/r/emacs/comments/185n3yo/emacs_meets_chatgpt_for_flawless_grammar_and/

#+begin_src emacs-lisp
(defun chatgpt-shell--region-or-paragraph ()
  "Return an alist with :start, :end, and :text for the active region or current paragraph."
  (if (use-region-p)
      (chatgpt-shell--region)
    (save-excursion
      (mark-paragraph)
      (let ((start (region-beginning))
            (end   (progn (goto-char (region-end))
                          (skip-chars-backward "\n")
                          (point))))
        (list (cons :start start)
              (cons :end   end)
              (cons :text  (buffer-substring-no-properties start end)))))))

(defun chatgpt-shell--region-or-paragraph-with-newline ()
  "Return an alist with :start, :end, and :text for the active region or current paragraph, with space for newline."
  (let ((region (chatgpt-shell--region-or-paragraph)))
    (save-excursion
      (goto-char (alist-get :start region))
      (insert "\n")
      (list (cons :start (+ 1 (alist-get :start region)))  ; start after inserted newline
            (cons :end   (+ 1 (alist-get :end region)))
            (cons :text  (alist-get :text region))))))

(defun chatgpt-shell-spell-check-region-or-paragraph ()
  "Correct spelling and grammar of the active region or current paragraph."
  (interactive)
  (let* ((region (chatgpt-shell--region-or-paragraph-with-newline))
         (query  (alist-get :text region)))
    (chatgpt-shell-request-and-insert-merged-response
     :system-prompt     "Correct only spelling and grammar. Preserve org-mode markup like =this= and *this*. Only return the corrected paragraph, not the original text or this prompt."
     :query             (substring query 1)  ; Remove the prepended newline from query
     :context           nil
     :remove-block-markers t
     :region            region
     :on-iterate        (lambda (output)
                          (set-mark   (alist-get :end region))
                          (goto-char  (alist-get :start region))
                          (chatgpt-shell-quick-insert
                           (list (cons (substring query 1) output)))))))

(defun chatgpt-shell-improve-clarity-region-or-paragraph ()
  "Improve clarity, spelling, and grammar of the active region or current paragraph."
  (interactive)
  (let* ((region (chatgpt-shell--region-or-paragraph-with-newline))
         (query  (alist-get :text region)))
    (chatgpt-shell-request-and-insert-merged-response
     :system-prompt     "Improve clarity, spelling, and grammar of the following text. Only return the corrected paragraph, not the original text or this prompt."
     :query             (substring query 1)  ; Remove the prepended newline from query
     :context           nil
     :remove-block-markers t
     :region            region
     :on-iterate        (lambda (output)
                          (set-mark   (alist-get :end region))
                          (goto-char  (alist-get :start region))
                          (chatgpt-shell-quick-insert
                           (list (cons (substring query 1) output)))))))

(defun chatgpt-shell-custom-prompt-region-or-paragraph ()
  "Apply a custom prompt to the active region or current paragraph."
  (interactive)
  (let* ((custom-prompt (read-string "Custom prompt: "))
         (full-prompt (concat custom-prompt " Only return the corrected paragraph, not the original text or this prompt."))
         (region (chatgpt-shell--region-or-paragraph-with-newline))
         (query  (alist-get :text region)))
    (chatgpt-shell-request-and-insert-merged-response
     :system-prompt     full-prompt
     :query             (substring query 1)  ; Remove the prepended newline from query
     :context           nil
     :remove-block-markers t
     :region            region
     :on-iterate        (lambda (output)
                          (set-mark   (alist-get :end region))
                          (goto-char  (alist-get :start region))
                          (chatgpt-shell-quick-insert
                           (list (cons (substring query 1) (concat "\n" output))))))))

(defun chatgpt-shell-proofread-or-improve ()
  "Prompt to either spell-check or improve clarity on region or paragraph."
  (interactive)
  (let ((choice
         (ivy-completing-read
          "Action: " '("Spell Check" "Improve Clarity" "Custom Prompt") nil t)))
    (pcase choice
      ("Spell Check"    (chatgpt-shell-spell-check-region-or-paragraph))
      ("Improve Clarity" (chatgpt-shell-improve-clarity-region-or-paragraph))
      ("Custom Prompt"   (chatgpt-shell-custom-prompt-region-or-paragraph))
      (_ (user-error "Invalid choice: %s" choice)))))

(global-set-key (kbd "C-c s") #'chatgpt-shell-proofread-or-improve)
#+end_src

Run an external Python script that collects the staged diff in the current Git repository, sends it to ChatGPT, and returns the recommended commit message. Bind to C-c s in git-commit-mode.

#+begin_src emacs-lisp
(defun run-gpt-commit ()
  "Run gpt-commit.py from repo root, setting OPENAI_API_KEY from ~/.netrc."
  (interactive)
  (let ((git-root (magit-toplevel)))
    (if (not git-root)
        (message "Not in a git repository")
      (let* ((default-directory git-root)
             (netrc-file (expand-file-name "~/.netrc"))
             (api-key
              (when (file-readable-p netrc-file)
                (with-temp-buffer
                  (insert-file-contents netrc-file)
                  (goto-char (point-min))
                  (when (re-search-forward "^machine[ \t]+api\\.openai\\.com\\b" nil t)
                    (when (re-search-forward "^\\s-*password[ \t]+\\(.+\\)$" nil t)
                      (match-string-no-properties 1)))))))
        (when (and api-key (not (string-empty-p api-key)))
          (setenv "OPENAI_API_KEY" api-key))
        (let* ((gpt-commit-script (expand-file-name "~/dev/gpt_commit.py"))
               (output (shell-command-to-string (format "python3 %s" gpt-commit-script))))
          (if (string-empty-p (string-trim output))
              (message "gpt-commit.py produced no output")
            (insert output)))))))

(with-eval-after-load 'git-commit
  (define-key git-commit-mode-map (kbd "C-c s") 'run-gpt-commit))
#+end_src

** Codeium

#+begin_src emacs-lisp
(add-to-list 'load-path "~/.emacs.d/codeium.el")
#+end_src

#+begin_src emacs-lisp
(use-package codeium
  :ensure nil
  :init
  ;; use globally
  ;; (add-to-list 'completion-at-point-functions #'codeium-completion-at-point)
  ;; or on a hook
  (add-hook 'python-mode-hook
      (lambda ()
          (setq-local completion-at-point-functions '(codeium-completion-at-point))))

  ;; codeium-completion-at-point is autoloaded, but you can
  ;; optionally set a timer, which might speed up things as the
  ;; codeium local language server takes ~0.2s to start up
  ;; (add-hook 'emacs-startup-hook
  ;;  (lambda () (run-with-timer 0.1 nil #'codeium-init)))

  ;; :defer t ;; lazy loading, if you want
  :config
  (setq use-dialog-box nil) ;; do not use popup boxes
  ;; Disable logging to *codeium-log* to eliminate spammy heartbeat messages.
  ;; You can always re-enable temporarily to debug problems.
  (setq codeium-log-buffer nil)

  ;; Read the API key from ~/.netrc using the built-in auto-source package
  (setq codeium/metadata/api_key
        (auth-source-pick-first-password :host "codeium" :type 'netrc))

  ;; get codeium status in the modeline
  (setq codeium-mode-line-enable
        (lambda (api) (not (memq api '(CancelRequest Heartbeat AcceptCompletion)))))
  (add-to-list 'mode-line-format '(:eval (car-safe codeium-mode-line)) t)
  ;; alternatively for a more extensive mode-line
  ;; (add-to-list 'mode-line-format '(-50 "" codeium-mode-line) t)

  ;; use M-x codeium-diagnose to see apis/fields that would be sent to the local language server
  (setq codeium-api-enabled
        (lambda (api)
          (memq api '(GetCompletions Heartbeat CancelRequest GetAuthToken RegisterUser auth-redirect AcceptCompletion))))
  ;; you can also set a config for a single buffer like this:
  ;; (add-hook 'python-mode-hook
  ;;     (lambda ()
  ;;         (setq-local codeium/editor_options/tab_size 4)))

  ;; You can overwrite all the codeium configs!
  ;; for example, we recommend limiting the string sent to codeium for better performance
  (defun my-codeium/document/text ()
    (buffer-substring-no-properties (max (- (point) 3000) (point-min)) (min (+ (point) 1000) (point-max))))
  ;; if you change the text, you should also change the cursor_offset
  ;; warning: this is measured by UTF-8 encoded bytes
  (defun my-codeium/document/cursor_offset ()
    (codeium-utf8-byte-length
     (buffer-substring-no-properties (max (- (point) 3000) (point-min)) (point))))
  (setq codeium/document/text 'my-codeium/document/text)
  (setq codeium/document/cursor_offset 'my-codeium/document/cursor_offset))
#+end_src
* External Tools and Integration

Enables editing any Chrome textarea inside Emacs by syncing the browser field to a dedicated Emacs buffer via the GhostText protocol. Requires the GhostText Chrome extension.

#+begin_src emacs-lisp
(use-package atomic-chrome
  :ensure t
  :init
  ;; Where the buffers should appear: 'frame, 'split, or 'full
  (setq atomic-chrome-buffer-open-style 'frame)
  :config
  (defun bordercore/strip-cr-from-string (text)
    "Return TEXT with all carriage returns removed."
    (replace-regexp-in-string "\r" "" text))

  ;; Strip CRs when the buffer is first created.
  (advice-add
   'atomic-chrome-create-buffer :around
   (lambda (orig-fun socket url title text)
     (funcall orig-fun socket url title
              (bordercore/strip-cr-from-string text))))

  ;; Strip CRs on every subsequent update from the browser.
  (advice-add
   'atomic-chrome-update-buffer :around
   (lambda (orig-fun socket text)
     (funcall orig-fun socket
              (bordercore/strip-cr-from-string text))))

  ;; Start the server so Chrome can talk to Emacs
  (atomic-chrome-start-server))
#+end_src

* Games
** Nethack

#+BEGIN_SRC emacs-lisp
(add-hook 'nethack-map-mode-hook
  (lambda ()
    (define-key nh-map-mode-map (kbd "<left>") 'nethack-command-west)
    (define-key nh-map-mode-map (kbd "<up>") 'nethack-command-north)
    (define-key nh-map-mode-map (kbd "<down>") 'nethack-command-south)
    (define-key nh-map-mode-map (kbd "<right>") 'nethack-command-east)
    (define-key nh-map-mode-map (kbd "<kp-add>") 'nethack-command-northwest)
    (define-key nh-map-mode-map (kbd "<prior>") 'nethack-command-northeast)
    (define-key nh-map-mode-map (kbd "<end>") 'nethack-command-southwest)
    (define-key nh-map-mode-map (kbd "<next>") 'nethack-command-southeast)
))

(add-to-list 'load-path "~/.emacs.d/elisp/nethack/")
(autoload 'nethack "nethack" "Play Nethack." t)
#+END_SRC

You'll need to apt-get this if using Ubuntu or Debian
#+BEGIN_SRC emacs-lisp
(setq nethack-program "/usr/games/nethack-lisp")
#+END_SRC

* Runtime Performance

Increase the GC threshold so that garbage collection happens less frequently.
This should help with LSP performance.

#+begin_src emacs-lisp
(setq gc-cons-threshold (* 100 1000 1000))
#+end_src

Increase the amount of data which Emacs reads from a process.
This should help with LSP performance.

#+begin_src emacs-lisp
(setq read-process-output-max (* 1024 1024))
#+end_src

* Theme

This should be run near the end, since custom face attributes are set in current-theme.el, which all already need to be defined.

I store my custom themes here.
#+BEGIN_SRC emacs-lisp
(setq custom-theme-directory "~/.emacs.d/themes/")
#+END_SRC

Load the current theme. The theme name should be stored in the environment
variable "EMACS_THEME".

Then make any customizations specified in current-theme-custom.el, which
should be a symlink that matches the current theme.
#+BEGIN_SRC emacs-lisp
(defun load-theme-from-env-var ()
  "Load the Emacs theme specified by the EMACS_THEME environment variable."
  (let ((theme-name (getenv "EMACS_THEME")))
    (if theme-name
        (load-theme (intern theme-name) t)
      (message "EMACS_THEME environment variable is not set."))))

(load-theme-from-env-var)

(dolist (file '("~/.emacs.d/themes/current-theme-custom.el"))
  (when (file-exists-p file)
    (load-file file))
  )
#+END_SRC

* Wrapup

Local or experimental settings are stored here
#+BEGIN_SRC emacs-lisp
(let ((local-settings "~/.emacs-local"))
(when (file-exists-p local-settings)
  (load-file local-settings))
)
#+END_SRC

Use "delight" to hide certain modes from the mode line. Keep this here since some modes need to be delighted at the end for them to take effect.
#+BEGIN_SRC emacs-lisp
(use-package delight
  :ensure t
  :delight
  (eldoc-mode nil t)
  (org-indent-mode nil org-indent)
  (text-scale-mode nil face-remap)
  (global-whitespace-mode))
#+END_SRC
